package:
    name: astropy
    version: "0.4.0"

source:
    fn: astropy-0.4.0.tar.gz
    url: http://pypi.python.org/packages/source/a/astropy/astropy-0.4.tar.gz

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
        - numpy
    run:
        - python
        - numpy

