package:
    name: numpy
    version: "1.8.1"

source:
    fn: numpy-1.8.1.tar.gz
    url: http://downloads.sourceforge.net/project/numpy/NumPy/1.8.1/numpy-1.8.1.tar.gz

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python

