package:
    name: pip
    version: "1.2.3" # real version number set during build

# no source section -- instead ez_setup.py is downloaded in the build

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - setuptools

